name: 8th
on:
  workflow_dispatch:
    inputs:
        titleCustom:
          description: type the title
          type: string
          required: true
          default: "Hello world"
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Title: ${{ inputs.titleCustom }}"