name: 8th
on:
  workflow_dispatch:
    inputs:
        titleCustom:
          description: type the title
          type: string
          required: true
          default: "Hello world"
        selectCustom:
          description: select value
          type: choice
          required: true
          options:
            - value1
            - value2
            - value3
          default: value2
        checkCustom:
          description: checkbox
          type: boolean
          required: false
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Title: ${{ inputs.titleCustom }}"