name: working with my action
on: workflow_dispatch
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: using action
        uses: ./.github/actions/mysteps