name: calling wf
on: 
    workflow_dispatch: #это вводит пользователь
      inputs:
        title:
          description: "custom title"
          type: string
          default: "testing text title"
          required: false
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      title: watafa anyway #это передается в вызываемый вф