name: working with docker
on: workflow_dispatch

jobs:
  with-services:
    runs-on: ubuntu-latest
    services:
      web:
        image: nginx:alpine
        ports:
          - 80:80
    steps:
      - name: Проверяем nginx
        run: |
          curl http://localhost:80