name: 4workflow 
on: 
  workflow_run:
    workflows: [3workflow]
    types:
      - completed

jobs: 
  success-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Display some text
        run: echo success
  failure-command:
    runs-on: ubuntu latest
    if: ${{ github.event.workflow_run.conclusion == 'failureS' }}
    steps:
      - run: echo fail
     