name: tenth
on: [push]
run-name: testing header of commit 
jobs:
  mujob:
    runs-on: ubuntu-latest
    steps:
      - name: first
        id: context-expression
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(job) }}'
      - name: second
        id: haha
        run: echo '${{ toJson(steps) }}'
